info:
  build:
    version: '@project.version@'
    name: '@project.name@'
    timestamp: '@maven.build.timestamp@'

server:
  port: 8080

logging:
  level:
    root: DEBUG

soap:
  calculator:
    host: http://localhost:7777/services/Calculator.CalculatorHttpSoapEndpoint/
    timeout: 2000
    pool:
      maxTotal: 20
      defaultMaxPerRoute: 15